config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :bookings do
    resources :tickets
  end
  resources :fights do
    resources :likes, module: :fights
    resources :comments, module: :fights
  end
  
  resources :events do
    resources :likes, module: :events
    resources :comments, module: :events
    resources :addresses, module: :events
    resources :sign_ups, module: :events
    resources :fights
    resources :bookings
  end
  
  resources :fight_records
  resources :fight_profiles
  resources :gyms do
    resources :likes, module: :gyms
    resources :addresses, module: :gyms
  end

  resources :sign_ups
  resources :addresses
  resources :notifications
  resources :likes
  resources :friend_requests do
    resources :friendships
  end

  resources :friendships
  resources :posts do
    resources :likes, module: :posts
    resources :comments, module: :posts
  end

  resources :comments do
    resources :likes, module: :comments
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  resources :users, only: [:show, :index] do
    member do
      delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
    end
  end

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true

  belongs_to :user, class_name: 'User', foreign_key: :user_id
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable, dependent: :destroy

end

app/controllers/comments/likes_controller.rb
class Comments::LikesController < LikesController
  before_action :set_likeable
    
  private
    
  def set_likeable
    @likeable = Comment.find(params[:comment_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create

    @comment = @commentable.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_back fallback_location: @commentable, notice: "Comment was successfully posted!" }
        format.json { render :show, status: :created, location: @comment }
        if @commentable.class == Event
          Notification.create(recipient_id: @commentable.host.owner.id, actor_id: current_user.id, action: 'commented on', notifiable: @commentable)
        else 
          Notification.create(recipient_id: @commentable.user.id, actor_id: current_user.id, action: 'commented on', notifiable: @commentable)
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @commentable, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def is_hosted
    self.host.present? ? true : false
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @commentable, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body)
    end
    
end

app/controllers/events/comments_controller.rb
class Events::CommentsController < CommentsController
  before_action :set_commentable
  
  private
  
  def set_commentable
    @commentable = Event.find(params[:event_id])
  end

end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments<h3>
<div class="flex flex-col shadow my-4">
  <div class="bg-gray-700 flex flex-col justify-end rounded-lg p-6">
    <% commentable.comments.each do |comment| %>
      <div>
        <p class="text-xl pb-4 rounded-lg">
          <%= comment.body %>
        </p>
        <p>
          <% if comment.user.username == "" %>
            <% user_label = comment.user.first_name + " " + post.user.last_name %>
          <% else %>
            <% user_label = comment.user.username %>
          <% end %>
          <a href="#" class="text=3x1 font-bold hover:text-gray-700 pb-4 border-blue-700 bg-transparent shadow-lg">
            <%= link_to "#{user_label}", user_path(comment.user_id), class: "text=3x1 font-bold hover:text-gray-700 pb-4 border-blue-700 bg-transparent shadow-lg" %>
          </a>     
          <div><%= image_tag comment.user.profile_picture, class: "rounded-full w-10 h-10 border-2 border-black" %></div>       
        </p>

      </div>
      <p>
        <% if comment.user_id == current_user.id %>
            <div><%= link_to "Edit", edit_post_path(comment) %></div>
        <% else %>
          <% pre_like = comment.likes.find { |like| like.liker_id == current_user.id } %>
          <% if pre_like %>
            <%= link_to "Un-Like (#{comment.likes.count})", like_path(pre_like), method: :delete, class: "bg-blue-500 text-white p-1 rounded-full hover:bg-black" %>
          <% else %>
            <%= render partial: 'likes/like_button', locals: { likeable: comment } %>
          <% end %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [commentable, Comment.new] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :body, placeholder: "Add a comment", input_html: { class: "text-area bg-gray-500 rounded-lg"} %>    
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn post" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Auther</th>
      <th>Body</th>
      <th>Commentable</th>
      <th>Commentable type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.commentable_id %></td>
        <td><%= comment.commentable_type %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Auther:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Commentable:</strong>
  <%= @comment.commentable_id %>
</p>

<p>
  <strong>Commentable type:</strong>
  <%= @comment.commentable_type %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>