config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :bookings do
    resources :tickets
  end
  resources :fights do
    resources :likes, module: :fights
    resources :comments, module: :fights
  end
  
  resources :events do
    resources :likes, module: :events
    resources :comments, module: :events
    resources :addresses, module: :events
    resources :sign_ups, module: :events
    resources :fights
    resources :bookings
  end
  
  resources :fight_records
  resources :fight_profiles
  resources :gyms do
    resources :likes, module: :gyms
    resources :addresses, module: :gyms
  end

  resources :sign_ups
  resources :addresses
  resources :notifications
  resources :likes
  resources :friend_requests do
    resources :friendships
  end

  resources :friendships
  resources :posts do
    resources :likes, module: :posts
    resources :comments, module: :posts
  end

  resources :comments do
    resources :likes, module: :comments
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  resources :users, only: [:show, :index] do
    member do
      delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
    end
  end

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :github]

  
  has_many :notifications, foreign_key: :recipient_id
  has_many :posts, dependent: :destroy
  has_many :comments, foreign_key: :user_id, dependent: :destroy
  has_many :likes, foreign_key: :liker_id, dependent: :destroy
  has_many :liked_posts, class_name: 'Post', through: :likes
  has_one_attached :avatar, dependent: :destroy
  validates :avatar, content_type: [:png, :jpg, :jpeg]
  has_many :friend_requests_as_requestor, foreign_key: :requestor_id, class_name: :FriendRequest, dependent: :destroy
  has_many :friend_requests_as_receiver, foreign_key: :receiver_id, class_name: :FriendRequest
  has_many :friendships, ->(user) { where("user_a_id = ? OR user_b_id = ?", user.id, user.id) }
  has_many :friends, through: :friendships
  has_many :gyms, foreign_key: :user_id
  has_one :gym, class_name: "Gym", foreign_key: "gym_id"
  has_many :fight_profiles, dependent: :destroy
  has_many :fight_records, dependent: :destroy
  has_many :sign_ups
  has_many :participations, class_name: "Event", through: :sign_ups
  has_many :bookings, dependent: :destroy
  has_many :tickets, through: :bookings
  
  

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.first_name = provider_data.info.first_name
      user.last_name = provider_data.info.last_name
      user.password = Devise.friendly_token[0, 20]
      user.provider_picture = provider_data.info.image
    end
  end

  def friends
    join_statement = <<-SQL
      INNER JOIN friendships
        ON (friendships.user_a_id = users.id OR friendships.user_b_id = users.id)
        AND (friendships.user_a_id = #{id} OR friendships.user_b_id = #{id})
    SQL
    User.joins(join_statement)
        .where.not(id: id)
  end

  def profile_picture
    if self.avatar.attached? && self.avatar.representable?
      avatar.variant(resize: '100x100').processed
    elsif provider_picture?
      provider_picture
    else
      "/assets/defaultprofile.png"
    end
  end

  def full_name
    "#{self.first_name} " + "#{self.last_name}"
  end

  def is_admin?
    self.admin?
  end

  after_create :welcome_send
  def welcome_send
    UserMailer.with(user: self).welcome_email.deliver_now
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  
  def index
    @users = User.all 
  end
    
  def show
    @user = User.find(params[:id])
  end

  def delete_image
    image = ActiveStorage::Attachment.find(params[:image_id])
    if current_user == image.record || current_user.is_admin?
      image.purge
      redirect_back(fallback_location: request.referer)
    else redirect_to root_url, notice: "Ah Ah Ah! You don't have permission to do that"
    end
  end
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
end

app/views/users/_fight_profile.html.erb
<%= @user.first_name %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-3xl font-bold pt-8 lg:pt-0">Users</h1>
<br>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'View Profile', user %></td>
        
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
  
  <div class="max-w-4xl flex items-center h-auto lg:h-screen flex-wrap mx-auto my-32 lg:my-0">
  
    <div class="p-4 md:p-12 text-center lg:text-left">
    <!-- Image for mobile view-->
			<div class="block lg:hidden rounded-full shadow-xl mx-auto -mt-16 h-48 w-48 bg-cover bg-center" style="background-image: url('https://source.unsplash.com/MP0IUfwrn0A')"></div>
			
      <a class="href">
        <%= image_tag @user.profile_picture, class: "rounded-full w-30 h-30 border-2 border-green-500 " %>
      </a>
      <br>
      <h1 class="text-3xl font-bold pt-8 lg:pt-0"> <%= @user.full_name %> </h1>
      <div class="mx-auto lg:mx-0 w-4/5 pt-3 border-b-2 border-green-500 opacity-25"></div>
      <p class="pt-4 text-base font-bold flex items-center justify-center lg:justify-start">
        <% if @user.fight_profiles.count > 0 %>
          <%= @user.fight_profiles.first.ring_name %>
        <% end %>
      </p>
      <p class="pt-8 text-sm"><%= @user.bio %></p><br>
      <% if @user == current_user %>
        <%= link_to 'Edit my info', edit_registration_path(@user), class: "btn post" %><br><br>
        <%= link_to 'Set up a new gym', new_gym_path, class: "btn post" %><br><br>
        <%= render 'friend_requests/pending_friend_requests' %><br>
        <h4>Notifications</h4><br>
        <%= render 'notifications/notifications' %><br>
        <% if @user.fight_profiles.count > 0 %>
          <%= link_to 'Edit your fight profile', edit_fight_profile_path(@user.fight_profiles.first.id), class: "btn post" %>
        <% else %>
          <%= link_to 'Set Up a fighter profile', new_fight_profile_path(), class: "btn post" %>
        <% end %>
        <br><br>
        <div>
        <% if @user.fight_profiles.exists? %>
          <table class="bg-transparent">
            <tr>
              <th class="p-2" scope="col">Ring Name:</th>
              <th class="p-2" scope="col">Style:</th>
              <th class="p-2" scope="col">Weight:</th>
              <th class="p-2" scope="col">Wins:</th>
              <th class="p-2" scope="col">Losses:</th>
              <th class="p-2" scope="col">Draws:</th>
            </tr>
            <% @user.fight_profiles.each do |fight_profile| %>
              <tr>
                <td class="p-2"><%= fight_profile.ring_name %></td>
                <td class="p-2"><%= fight_profile.style.name %></td>
                <td class="p-2"><%= fight_profile.fight_weight %></td>
                <% if @user.fight_records.exists? %>
                  <td class="p-2"><%= fight_profile.user.fight_records.first.win %></td>
                  <td class="p-2"><%= fight_profile.user.fight_records.first.lose %></td>
                  <td class="p-2"><%= fight_profile.user.fight_records.first.draw %></td>
                <% else %>
                  <td class="p-2">0</td>
                  <td class="p-2">0</td>
                  <td class="p-2">0</td>
                <% end %>
              </tr>
            <% end %>
          </table>
        <% end %>
      </div>
      <% else %>
        <% if Friendship.exists?(user_a_id: current_user.id, user_b_id: @user.id) || Friendship.exists?(user_a_id: @user.id, user_b_id: current_user.id) %>
          <div class="pt-12 pb-8">
				    <button class="bg-green-700 hover:bg-green-900 text-white font-bold py-2 px-4 rounded-full">
				      <%= button_to 'Un Friend!', friendship_path, method: :delete, class: "btn post"  %>
				    </button> 
			    </div>
        <% elsif FriendRequest.exists?(requestor_id: current_user.id, receiver_id: @user.id) || FriendRequest.exists?(requestor_id: @user.id, receiver_id: current_user.id) %>
          <p> There is already a pending friendship request between the two of you, one of you needs to sort it.... </p>
        <% else %>
          <div class="pt-12 pb-8">
				    <button >
				      <%= button_to 'Add friend', friend_requests_path, method: :post, params: { receiver_id: @user.id }, class: "btn post" %>
				    </button> 
			    </div>
          
        <% end %>
      <% end %>
      <div>
      
      </div>
      <br>
      <div>
        <p>Here are all of <%=@user.first_name%>'s posts</p><br>
          <table class="bg-transparent">
            <thead>
              <tr>
                <th class="p-2" colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @user.posts.each do |post| %>
                <tr>
                  <td class="p-2 border-gray-800 rounded-full border-2"><%= post.body %></td>
                  <td class="p-2 border-gray-800 rounded-full border-2"><%= post.created_at %></td>
                  
                </tr>
              <% end %>
            </tbody>
          </table>      
       </div>
    </div>
  </div>
<div>
  
</div>