config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :bookings do
    resources :tickets
  end
  resources :fights do
    resources :likes, module: :fights
    resources :comments, module: :fights
  end
  
  resources :events do
    resources :likes, module: :events
    resources :comments, module: :events
    resources :addresses, module: :events
    resources :sign_ups, module: :events
    resources :fights
    resources :bookings
  end
  
  resources :fight_records
  resources :fight_profiles
  resources :gyms do
    resources :likes, module: :gyms
    resources :addresses, module: :gyms
  end

  resources :sign_ups
  resources :addresses
  resources :notifications
  resources :likes
  resources :friend_requests do
    resources :friendships
  end

  resources :friendships
  resources :posts do
    resources :likes, module: :posts
    resources :comments, module: :posts
  end

  resources :comments do
    resources :likes, module: :comments
  end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  resources :users, only: [:show, :index] do
    member do
      delete 'delete_image/:image_id', action: 'delete_image', as: 'delete_image'
    end
  end

  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :host, class_name: "Gym", foreign_key: "gym_id"
  has_many :fights, class_name: "Fight", foreign_key: "event_id"
  has_many :users, class_name: "User", :through => :fights
  has_many :addresses, as: :hostable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :sign_ups
  has_many :users, through: :sign_ups
  has_many :bookings, dependent: :destroy
  has_many :tickets, :through => :bookings
  
  def upcoming?
    self.event_date > Time.now
  end

  def tickets_remaining
    self.num_tickets - self.tickets.count
  end
  
end

app/controllers/events/addresses_controller.rb
class Events::AddressesController < AddressesController
  before_action :set_hostable
        
  private
      
  def set_hostable
    @hostable = Event.find(params[:event_id])
  end
end

app/controllers/events/comments_controller.rb
class Events::CommentsController < CommentsController
  before_action :set_commentable
  
  private
  
  def set_commentable
    @commentable = Event.find(params[:event_id])
  end

end

app/controllers/events/likes_controller.rb
class Events::LikesController < LikesController
  before_action :set_likeable
      
  private
      
  def set_likeable
    @likeable = Event.find(params[:event_id])
  end
end

app/controllers/events/sign_ups_controller.rb
class Events::SignUpsController < SignUpsController
  before_action :set_sign_upable
        
  private
        
  def set_sign_upable
    @sign_upable = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all.order(event_date: :desc)
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:gym_id, :event_date, :num_tickets, :ticket_price, :event_name, :event_info)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
  
<div class="bg-transparent flex flex-col justify-end rounded-lg p-6 border-green-900 border-2">
    <div>
      <div class="bg-gray-900 flex flex-col justify-start p-6 rounded-lg shadow-2xl">
        <div class="flex flex-row">
          <div class="">
            <a class="href">
              <% if event.host.avatar.attached?%>
                <%= image_tag event.host.avatar, class: "rounded-full w-30 h-30 border-2 border-green-500 " %>
              <% end %>
            </a>
          </div>
          <div class="bg-gray-900 flex flex-col justify-start p-6 rounded-lg shadow-2xl">
            <div class="p-1">
              <%= link_to 'View Event', event_path(event), class: "btn post" %>
            </div>
            <p class="text-xl pb-4">
              <strong>Event name:</strong>
              <%= event.event_name %>
            </p>
            <p class="text-xl pb-4">
              <strong>Event date:</strong>
              <%= event.event_date %>
            </p>
            <p class="text-xl pb-4">
              <strong>Event info:</strong>
              <%= event.event_info %>
            </p> 
            <p class="text-l pb-4">
              <strong>Hosting Gym:</strong>
              <%= event.host.name %>
            </p>            
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs p-10 flex-col flex-wrap items-center space-y-2">
    <%= f.input :gym_id, collection: current_user.gyms.all, prompt: "Which gym are you creating the event for?", input_html: { class: "frm" }, require: true %>
    <%= f.input :event_date, input_html: { class: "text-area frm" } %>
    <%= f.input :event_name, input_html: { class: "text-area frm" } %>
    <%= f.input :event_info, input_html: { class: "text-area frm" } %>
    <%= f.input :num_tickets, input_html: { class: "frm" } %>
    <%= f.input :ticket_price, input_html: { class: "frm" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn post" %>
  </div>
<% end %>

app/views/events/_host_view.html.erb
<p id="notice"><%= notice %></p>
<div class="w-full container mx-auto bg-grey-900 shadow-outline">
  <div>
    <table class="bg-transparent mx-auto">
      
      <tr>
        <td class="px-10 text-xl text-center"><%= @event.sign_ups.count %></td>
        <td class="p-1 text-xl text-center"><%= (@event.sign_ups.count)-(@event.fights.count*2) %></td>
        <td class="p-1 text-xl text-center"><%= @event.num_tickets - @event.tickets_remaining %></td>
        <td class="p-1 text-xl text-center"><%= @event.tickets_remaining %></td>
      </tr>
      <tr>
        <th class="px-10 text-xs text-center">Fighters Signed Up</th>
        <th class="px-10 text-xs text-center">Fighters Not Yet Matched</th>
        <th class="px-10 text-xs text-center">Tickets Sold</th>
        <th class="px-10 text-xs text-center">Tickets Left</th>
      </tr>
    </table>
  </div>
  <div class="flex flex-row flex-auto space-x-10 place-content-between shadow-2xl" >
    <div class="shadow-inner w-full container flex flex-col items-center h-auto bg-gradient-to-t from-gray-400 via-green-800 to-gray-800 mx-auto rounded-lg border-green-200 border-opacity-10 ">
      <h1 class="p-10 font-serif bg-transparent text-8xl text-center"><%= @event.event_name %> </h1>
      <br>
      <br>
      <p class="flex auto items-center p-5 h-auto bg-transparent text-2xl">
        <%= @event.event_info %>
      </p>
      <br>
      <br>
      <p class="flex auto items-center p-5 h-auto bg-transparent">
        <strong class="text-4xl">Fights</strong>
          <% if @event.fights.count > 0 %>
            <table class="bg-transparent">
              <tr>
                <th class="p-2">Fighter A:</th>
                <th class="p-2">Fighter B:</th>
                <th class="p-2">Update:</th>
              </tr>              
              <% fight = @event.fights.each do |f| %>
                <tr>
                  <td class="p-2"><%= f.fighter_a.user.full_name %></td>
                  <td class="p-2"><%= f.fighter_b.user.full_name %></td>
                  <td class="p-2"><%= link_to 'Update', edit_fight_path(f), class: "btn post" %></td>
                </tr>
              <% end %>
            </table>
        <% else %>
          <p> This event will be a flop if you don't schedule some fights fool
          </p>
        <% end %>
      </p>
      <br>
      <br>
      <p class="flex auto items-center p-1 h-auto bg-transparent">
        <strong class="text-2xl">Date - <%= @event.event_date %></strong>
        
      </p>
      <br>
      <br>
      <p class="flex-auto items-center p-1  h-auto bg-transparent">
        <% if @event.host.addresses.count > 0 %>
          <strong>Address:</strong>
              <% @event.host.addresses.each do |address| %>
                  <p><%= address.address1 %></p>
                  <p><%= address.address2 %></p>
                  <p><%= address.town_or_city %></p>
                  <p><%= address.county %></p>
                  <p><%= address.post_code %></p>
                  <p><%= address.country %></p>
              <% end %>
        <% else %>
          <strong class="text-2xl">Address - To be Confirmed</strong>
        <% end %>
      </p>
      

      
      <div class="flex flex-col items-center">
        <div class=" flex space-y-10">
          <div>
            <%= link_to "Edit", edit_event_path(@event), class: "btn post" %><br><br>
            <div class="p-1 text-white text-xl bg-green-900 border-2 border-white rounded-lg" >
              <h2 >Add a fight to this event</h2>
              <%= render 'fights/form', event: @event %>
              <br>
              <table class="bg-transparent p-2">
                <h4>Fighters signed up for this event</h4>
                <tr class="p-1">
                  <th class="p-2">Fighter Name:</th>
                  <th class="p-2">Gym:</th>
                  <th class="p-2">Weight:</th>
                  <th class="p-2">Email:</th>
                </tr>
                <% @event.users.each do |user| %>
                  <tr>
                    <td class="p-2"><%= user.full_name %></td>              
                    <td class="p-2"><%= user.fight_profiles.first.gym.name %></td>
                    <td class="p-2"><%= user.fight_profiles.first.fight_weight %></td>
                    <td class="p-2"><%= user.email %></td>
                  </tr>
                <% end %>
              </table>
            </div>
          </div>
          
        </div>
        <p>
          <%= link_to 'Visit this gyms page for other events and info', gym_path(@event.host) %>
        </p>
        <p>
          <%= link_to 'Back to Events', events_path %>
        </p>
      </div>

      <div class="flex flex-col items-center">
        <%= render partial: 'comments/comments', locals: { commentable: @event }, class: "bg-transparent" %>         
      </div>
      <div class="flex flex-col items-center">
        <%= render partial: 'comments/form', locals: { commentable: @event } %>
      </div>
    </div>
  </div>
</div>

app/views/events/_std_view.html.erb
<p id="notice"><%= notice %></p>
<div class="w-full container mx-auto bg-grey-900 shadow-outline">
  <div class="flex flex-row flex-auto space-x-10 place-content-between shadow-2xl" >
    <div class="shadow-inner w-full container flex flex-col items-center h-auto bg-gradient-to-t from-gray-400 via-green-800 to-gray-800 mx-auto rounded-lg border-green-200 border-opacity-10 ">
      <h1 class="p-10 font-serif bg-transparent text-8xl text-center"><%= @event.event_name %> </h1>
      <br>
      <br>
      <p class="flex auto items-center p-5 h-auto bg-transparent text-2xl">
        <div><%= @event.event_info %></div><br><br>
        <div> 
          <% if @event.tickets_remaining > 0 %>
            <%= "Tickets Remaining #{@event.tickets_remaining}" %>
            <%= render partial: 'bookings/form', locals: { event: @event } %>
            <%= "£#{@event.ticket_price} per ticket" %>
          <% else %>
            <p>This Event is sold out!</p>
          <% end %>
        </div>
      </p>
      <br>
      <br>
      <p class="flex auto items-center p-5 h-auto bg-transparent">
        <strong class="text-4xl">Fights will include this epic showdown!</strong>
        <% if @event.fights.count > 0 %>
          <% @event.fights.each do |fight| %>
            <div class="flex flex-row flex-auto space-x-10 place-content-between shadow-2xl">
              <div class="flex flex-col">
                <div class="w-full flex flex-col items-center px-3">
                  <a class="href">
                    <%= image_tag fight.fighter_a.user.profile_picture, class: "rounded-lg w-10 h-10 border-2 border-transparent hover:border-indigo-400 text-white " %>
                  </a>
                  <p>
                    <%= fight.fighter_a.ring_name %>
                  </p>
                </div>
              </div>
              <div class="flex flex-col">
                <div class="w-full flex flex-col items-center px-3">
                  <a class="href">
                    <%= image_tag fight.fighter_b.user.profile_picture, class: "rounded-lg w-10 h-10 border-2 border-transparent hover:border-indigo-400 text-white" %>
                  </a>
                  <p>
                    <%= fight.fighter_b.ring_name %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p> There are no fights scheduled for this event just yet, please check back soon
          </p>
        <% end %>
      </p>
      <p class="flex auto items-center p-1 h-auto bg-transparent">
        <strong class="text-2xl">Hosted by - <%= @event.host.name %></strong>
        
      </p>
      <br>
      <br>
      <p class="flex auto items-center p-1 h-auto bg-transparent">
        <strong class="text-2xl">Date - <%= @event.event_date %></strong>
        
      </p>
      <br>
      <br>
      <p class="flex-auto items-center p-1  h-auto bg-transparent">
        <% if @event.host.addresses.count > 0 %>
          <strong>Address:</strong>
              <% @event.host.addresses.each do |address| %>
                  <p><%= address.address1 %></p>
                  <p><%= address.address2 %></p>
                  <p><%= address.town_or_city %></p>
                  <p><%= address.county %></p>
                  <p><%= address.post_code %></p>
                  <p><%= address.country %></p>
              <% end %>
        <% else %>
          <strong class="text-2xl">Address - To be Confirmed</strong>
        <% end %>
      </p>
      

      
      <div class="flex flex-col items-center">
        <div class="flex flex-row items-center p-1 space-x-2">
            <% pre_like = @event.likes.find { |like| like.liker_id == current_user.id } %>
            <% if pre_like %>
              <%= link_to "Un-Like (#{@event.likes.count})", like_path(pre_like), method: :delete, class: "btn like unlike" %>
            <% else %>
              <%= render partial: 'likes/like_button', locals: { likeable: @event } %>
            <% end %>
            <% pre_sign = @event.sign_ups.find { |sign| sign.user_id == current_user.id } %>
            <% if pre_sign %>
              <%= link_to 'Quit This Event', sign_up_path(pre_sign), method: :delete, class: "btn post" %>
            <% else %>
              <%= render partial: 'sign_ups/sign_up_button', locals: { sign_upable: @event } %>              
            <% end %>
        </div>
        <p>
          <%= link_to 'Visit this gyms page for other events and info', gym_path(@event.host), class: "color-blue-500" %>
        </p>
        <p>
          <%= link_to 'Back to Events', events_path %>
        </p>
      </div>

      <div class="flex flex-col items-center">
        <%= render partial: 'comments/comments', locals: { commentable: @event }, class: "bg-transparent" %>         
      </div>
      <div class="flex flex-col items-center">
        <%= render partial: 'comments/form', locals: { commentable: @event } %>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= render partial: 'addresses/form', locals: { hostable: @event }  %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', event_path(@event) %>

app/views/events/index.html.erb
<div class="w-full container mx-auto bg-grey-900 shadow-outline">
  <div class="flex md-flex-row flex-auto space-x-10 place-content-between shadow-2xl" >

    <div class="flex flex-col items-center space-x-1 space-y-10 py-12 w-full">
      <div class="bg-gray-700 flex flex-col rounded-lg p-6 border-white border-2">
        <div class="bg-transparent w-full flex flex-col items-center text-2xl px-3">
          <h1>Events!</h1>
        </div>
      </div>

      <% @events.each do |event| %>
        <div  class="bg-gray-900 w-full md:w-2/3 flex flex-col items-center px-3">
          <%= render partial: 'event', locals: { event: event } %>
        </div>
      <% end %>         
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', gym_path(current_user.gyms.first.id) %>

app/views/events/show.html.erb
<% if current_user == @event.host.owner %>
  <%= render partial: 'events/host_view', locals: { event: @event } %>
<% else %>
  <%= render partial: 'events/std_view', locals: { event: @event } %>
<% end %>